version: '3.8'

services:
  workto-backend:
    image: workto-backend:latest
    container_name: workto-backend
    ports:
      - "10008:10008"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - /home/rusty/workto/workto-backend/src/main/resources/key/keyfile.properties:/app/keyfile.properties
